//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageDynamc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cumplimiento
    {
        public int Id { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> IdIndicadorResponsable { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Observacion { get; set; }
        public Nullable<decimal> Meta { get; set; }
    }
}
