//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageDynamc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicadorEvento
    {
        public int Id { get; set; }
        public Nullable<int> IdIndicador { get; set; }
        public Nullable<System.DateTime> Desde { get; set; }
        public Nullable<System.DateTime> Hasta { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> IsActivo { get; set; }
    }
}
