//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PageDynamc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsable
    {
        public int Id { get; set; }
        public Nullable<int> IdNivel { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Alias { get; set; }
    }
}
